# Config override for deployment
version: '3'

services:
  site:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.protocol=http"
    - "traefik.port=8779"
    - "traefik.frontend.rule=Host:generator.wom.social"
    - "traefik.frontend.entryPoints=http,https"
